message: Fixed behavior of ``asyncio.create_subproess_exec()``.
pr_ids:
- '61'
timestamp: 1636289056
type: bug
